# Generated by Django 3.2.3 on 2021-05-23 06:09

from django.db import migrations, models
import django_geogebra.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', django_geogebra.fields.GeoGebraCalculatorField()),
            ],
        ),
    ]
